### ISSUE TITLE
Tests unittests/map.cpp compile error under VS2013/VS2015 with boost 1.6X

### ISSUE THREAD

**Issue by stevehickman** [USCiLab/cereal#280] opened 2016-04-27 20:42 UTC
VS apparently does not define stream operators for std::pair. Compiling map.cpp results in:
  ```
map.cpp
1>d:\boost\boost_1_61_0_b1\boost\test\tools\detail\print_helper.hpp(47): error C2338: Type has to implement operator<< to be printable
1>  d:\boost\boost_1_61_0_b1\boost\test\tools\detail\print_helper.hpp(178): note: see reference to class template instantiation 'boost::test_tools::tt_detail::print_log_value<T>' being compiled
1>          with
1>          [
1>              T=std::pair<const std::string,int>
1>          ]
1>  d:\boost\boost_1_61_0_b1\boost\test\utils\wrap_stringstream.hpp(66): note: see reference to function template instantiation 'std::ostream &boost::test_tools::tt_detail::operator <<<std::pair<const _Kty,_Ty>>(std::ostream &,const boost::test_tools::tt_detail::print_helper_t<std::pair<const _Kty,_Ty>> &)' being compiled
1>          with
1>          [
1>              _Kty=std::string,
1>              _Ty=int
1>          ]
1>  d:\boost\boost_1_61_0_b1\boost\test\tools\old\impl.hpp(213): note: see reference to function template instantiation 'boost::basic_wrap_stringstream<char> &boost::operator <<<char,boost::test_tools::tt_detail::print_helper_t<std::pair<const _Kty,_Ty>>>(boost::basic_wrap_stringstream<char> &,const T &)' being compiled
1>          with
1>          [
1>              _Kty=std::string,
1>              _Ty=int,
1>              T=boost::test_tools::tt_detail::print_helper_t<std::pair<const std::string,int>>
1>          ]

```
One way to eliminate this problem is to add the following to the top of map.cpp:

```
typedef  std::pair<const std::string, int>       str_int_map_type;
BOOST_TEST_DONT_PRINT_LOG_VALUE(StructBase)
BOOST_TEST_DONT_PRINT_LOG_VALUE(str_int_map_type)

```
See this `[link  ](http://www.boost.org/doc/libs/1_60_0/libs/test/doc/html/boost_test/test_output/testing_tool_output_disable.html)`for documentation.

**Comment by stevehickman** [comment] 2016-05-01 01:25
Made a typo on the solution. Add the following to map.cpp:

typedef  std::pair<const std::string, int>       str_int_map_type;
BOOST_TEST_DONT_PRINT_LOG_VALUE(StructBase)
BOOST_TEST_DONT_PRINT_LOG_VALUE(str_int_map_type)

**Comment by stevehickman** [comment] 2016-05-25 14:42
I see my typo correction didn't actually correct anything. The typedef should be:
typedef std::pair<const std::string,int> str_int_map_type;

**Comment by AzothAmmo** [comment] 2016-06-01 04:51
I can't reproduce this with 2013 and boost 1.55 but I feel like I've run into this before (and fixed it before). I think it's related to using a later version of boost - will install 1.6 or later and check again.

**Comment by stevehickman** [comment] 2016-06-01 11:01
As you can see from the listing above, I was using Boost 1.61.0 beta 1.

**Comment by AzothAmmo** [comment] 2016-06-07 21:34
Were you encountering this under the latest release/master or the develop branch? I think this was fixed on develop a while back (see comment on #295).

**Comment by stevehickman** [comment] 2016-06-08 00:40
You appear to be correct. This is fixed in develop branch version as of June 7, 2016 (Commit: 8401da04af3c38678bb2173a5798c44cbf719aa3 [8401da0]) - may have been fixed before this.

**Closed** 2016-06-08 16:52 UTC
Labels: bug
