### ISSUE TITLE
CEREAL_REGISTER_POLYMORPHIC_RELATION fails to register relation under VS2015

### ISSUE THREAD

**Issue by ChrisBFX** [USCiLab/cereal#356] opened 2016-11-07 15:45 UTC
I get the "Trying to save a registered polymorphic type with an unregistered polymorphic cast. " exception when I want to serialize a base-class which has multiple derived classes, even when the relations are registered via CEREAL_REGISTER_POLYMORPHIC_RELATION.
It seems like PolymorphicVirtualCaster() doesn't registers all relations.

I also tested the develop branch which has the same behavior. (it works fine under gcc 4.9 though).

For testing I added:
```
CEREAL_REGISTER_TYPE(Base)
struct YourType2 : public YourType
{
	

	template<class Archive>
	void save(Archive & ar) const
	{
		std::cout << "Saving YourType2" << std::endl;
	}

	template<class Archive>
	void load(Archive & ar)
	{
		std::cout << "Loading YourType2" << std::endl;
	}
};

CEREAL_REGISTER_TYPE(YourType2)
CEREAL_REGISTER_POLYMORPHIC_RELATION(YourType, YourType2)


struct YourType3 : public YourType
{
	

	template<class Archive>
	void save(Archive & ar) const
	{
		std::cout << "Saving YourType3" << std::endl;
	}

	template<class Archive>
	void load(Archive & ar)
	{
		std::cout << "Loading YourType3" << std::endl;
	}
};

CEREAL_REGISTER_TYPE(YourType3)
CEREAL_REGISTER_POLYMORPHIC_RELATION(YourType, YourType3) 
```

to the rtti test, and saved instances of YourType2 and YourType3.

**Comment by AzothAmmo** [comment] 2016-11-07 21:27
You only see this behavior with MSVC 2015? I can't reproduce this with any version of clang or gcc under linux.

**Comment by ChrisBFX** [comment] 2016-11-09 11:01
Yes, and the fun thing is it even works in MSVC2013.

**Comment by AzothAmmo** [comment] 2016-11-28 18:52
Quick update on this: I'll be able to make better progress on MSVC issues soon since we'll be dropping the boost requirement for building the unit tests, which was delaying a few things.

**Comment by AzothAmmo** [comment] 2017-01-27 18:35
Blocking the next immediate release (1.2.2) until this is fixed.

**Comment by AzothAmmo** [comment] 2017-02-12 07:23
I've identified the cause of this error and will patch it soon. It should have actually been an error for other compilers as well, but we lucked out in the ordering of static initialization.

**Comment by AzothAmmo** [comment] 2017-02-12 08:28
Appveyor is still running but so far this looks good, I'm closing as fixed - let me know if the issue persists. I'll push this out as the next release within a few days.

**Closed by AzothAmmo** 2017-02-12 08:28 UTC
Labels: blocking, bug, Windows
