### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by pfeatherstone** [USCiLab/cereal#573] opened 2019-05-27 13:26 UTC
The build fails with the following output

<user>:~/Downloads/cereal$ mkdir release
<user>:~/Downloads/cereal$ cd release/
<user>:~/Downloads/cereal/release$ cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   serialization
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Configuring done
-- Generating done
-- Build files have been written to: <user>/Downloads/cereal/release
<user>:~/Downloads/cereal/release$ make
Scanning dependencies of target test_pair
[  1%] Building CXX object unittests/CMakeFiles/test_pair.dir/pair.cpp.o
In file included from <user>/Downloads/cereal/unittests/common.hpp:54:0,
                 from <user>/Downloads/cereal/unittests/pair.hpp:29,
                 from<user>/Downloads/cereal/unittests/pair.cpp:28:
<user>/Downloads/cereal/./include/cereal/archives/json.hpp: In member function ‘void cereal::JSONOutputArchive::finishNode()’:
<user>/Downloads/cereal/./include/cereal/archives/json.hpp:211:33: error: this statement may fall through [-Werror=implicit-fallthrough=]
             itsWriter.StartArray();
             ~~~~~~~~~~~~~~~~~~~~^~
<user>/Downloads/cereal/./include/cereal/archives/json.hpp:212:11: note: here
           case NodeType::InArray:
           ^~~~
<user>/Downloads/cereal/./include/cereal/archives/json.hpp:216:34: error: this statement may fall through [-Werror=implicit-fallthrough=]
             itsWriter.StartObject();
             ~~~~~~~~~~~~~~~~~~~~~^~
<user>/Downloads/cereal/./include/cereal/archives/json.hpp:217:11: note: here
           case NodeType::InObject:
           ^~~~
cc1plus: all warnings being treated as errors
unittests/CMakeFiles/test_pair.dir/build.make:62: recipe for target 'unittests/CMakeFiles/test_pair.dir/pair.cpp.o' failed
make[2]: *** [unittests/CMakeFiles/test_pair.dir/pair.cpp.o] Error 1
CMakeFiles/Makefile2:909: recipe for target 'unittests/CMakeFiles/test_pair.dir/all' failed
make[1]: *** [unittests/CMakeFiles/test_pair.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by furkanusta** [comment] 2019-05-27 14:03
This seems to be duplicate of #550 and #464

**Comment by pfeatherstone** [comment] 2019-05-27 14:19
Thank you

**Comment by AzothAmmo** [comment] 2019-05-27 18:21
There's actually quite a few compilers we are currently failing to build on, mostly due to new(ish) warnings. I updated CI about a week ago to highlight all of these so they can be fixed: https://travis-ci.com/USCiLab/cereal

**Closed** 2019-10-23 02:36 UTC
Labels: duplicate
