### ISSUE TITLE
Possible to use with windows dll files

### ISSUE THREAD

**Issue by runarundheim** [USCiLab/cereal#113] opened 2014-08-06 07:41 UTC
Today it is not possible to use cereal when serialization classes exist in different windows dll files.
The problem seems to be that each dll files get their own instance of the cereal::detail::StaticObject.

I think that to fix this it must be possible to set the dllexport/dllimport storage-class attributes on the cereal::detail::StaticObject<T> to make sure access is done only through one dll file. And it must also be possible to instantiate the cereal::detail::StaticObject<T> in a cpp file.

## Example

**base.h**
```cpp
#pragma once 
#include < memory > 
#include < cereal/cereal.hpp > 
#include < cereal/archives/binary.hpp > 
#include < cereal/types/polymorphic.hpp > 

#if defined (_WINDLL) 
  #define DECLSPECIFIER __declspec(dllexport) 
#else 
  #define DECLSPECIFIER __declspec(dllimport) 
#endif 

class Base /*abstract*/ 
{ 
  public: 
    friend class cereal::access; 
    template < class Archive > 
    DECLSPECIFIER void serialize(Archive & ar, std::uint32_t const version); 
    virtual ~Base() {} 
}; 
extern template DECLSPECIFIER void Base::serialize<cereal::BinaryOutputArchive>
     ( cereal::BinaryOutputArchive & ar, std::uint32_t const version ); 
```

**base.cpp**
```cpp
#include "Base.h" 
CEREAL_REGISTER_TYPE(Base) 
template void Base::serialize<cereal::BinaryOutputArchive>
    ( cereal::BinaryOutputArchive & ar, std::uint32_t const version ); 

template <class Archive> 
void Base::serialize(Archive & ar, std::uint32_t const version) 
{ 
} 
```

**derived.h**
```cpp
#pragma once 
#include "Base.h" 
class Derived : public Base 
{ 
  private: 
    friend class cereal::access; 
    template <class Archive> 
    void serialize(Archive & ar, std::uint32_t const version); 
}; 
extern template DECLSPECIFIER void Derived::serialize<cereal::BinaryOutputArchive>
    ( cereal::BinaryOutputArchive & ar, std::uint32_t const version ); 
```

**derived.cpp**
```cpp
#include "Derived.h" 

CEREAL_REGISTER_TYPE(Derived) 

template void Derived::serialize<cereal::BinaryOutputArchive>
    ( cereal::BinaryOutputArchive & ar, std::uint32_t const version ); 

template <class Archive> 
void Derived::serialize(Archive & ar, std::uint32_t const version) 
{ 
  ar(cereal::base_class<Base>(this)); 
} 
```

**main.cpp**
```cpp
#include "Derived.h" 
void main() 
{ 
  std::shared_ptr<Base> root(new Derived()); 
  std::stringstream ss; 
  cereal::BinaryOutputArchive oarchive(ss); 
  oarchive(root); 
} 
```

**problem**
Project 1: Containts the base.* and derived.* and create a dll file. This dll is used by project 2
Project 2: Only contain main.cpp and link in the dll from project 1

When program is run the oarchive(root) will throw an "Trying to save an unregistered polymorphic type (class Derived)"

**Comment by AzothAmmo** [comment] 2015-01-03 09:05
Just a quick update on this - putting some time towards this again and have the following requirements for a solution:

1. Allows a user to use polymorphic types registered in a DLL
2. Allows a user to register and use polymorphic types that are independent of the DLL, even when a DLL is used
3. Minimal amount of boilerplate to the user - I'm OK with things like `CEREAL_DLL_USE` and `CEREAL_DLL_MAKE` or something.  One other solution I'm playing with requires that the user use a `REGISTER_TYPE_DLL` both in and out of the DLL - not too sure I like that idea.

Also note that you can get away with not having to instantiate for all archive types if you move or provide a generic serialization function in the header.

----

For anyone who wants to contribute, the problem is the following: 

We need to have a single instance of the mapping from archives to polymorphic types across DLLs.  We use the `StaticObject` class to create a singleton.  On Windows this `StaticObject`, when placed in a DLL, will not be exported by default.  So this requires using `__declspec(dllexport)`.  Unfortunately it also isn't imported unless you fail to provide a definition and use `__declspec(dllimport)` (Fair warning: I could be wrong on some of this Windows specific stuff).  So our problem is how to balance this import/export nonsense and still allow people to use these `StaticObjects` without requiring that all of them be in the DLL.

**Comment by AzothAmmo** [comment] 2015-01-13 07:51
I have a potential solution for this: I've taken some changes from this a request (f29728b442785332ca37956dda972de424612d9e) that allow for `CEREAL_REGISTER_TYPE` macros to safely appear in multiple compilation units, meaning that they can be moved into headers.

The `CEREAL_REGISTER_TYPE` macro has a requirement that all archives that will be used with the type are included before the appearance of the macro.  Since you are making a DLL and already have to include the relevant archives (e.g. binary in your example), the macro will work without issue.

What ends up happening after this change is that both your DLL and main program will instantiate identical versions of the `StaticObject`s.  So we have a little bit of memory wasted here, but the main program will have access to a correctly filled `StaticObject` with no linker complaints.  The program behaves correctly and the serialization code itself resides within the DLL.

If this sounds fine, I'm going to merge the code and close out this and the versioning issue together.

**Comment by runarundheim** [comment] 2015-01-14 10:57
I think it sounds fine :) Dll files are very Windows specific and this will not create any special windows code in cereal.

**Comment by AzothAmmo** [comment] 2015-01-15 23:25
Should be fixed on branch issues_113_137, will be merged into develop soon.

**Comment by AzothAmmo** [comment] 2015-01-17 08:52
fixed on develop (6e41ed80b8f8045c23745dea23a535c5ae688d78)

**Closed by AzothAmmo** 2015-01-17 08:52 UTC
Labels: bug, Windows

**Comment by Dysl3xik** [comment] 2018-02-09 21:06
This bug appears to be alive again using VS2017 /std: latest, the sandbox_vs project unit test does not pass due to being unable to find the polymorphic call chain for Base -> Derived

**Comment by Dekken** [comment] 2018-03-13 13:06
I think I'm seeing this now
